#DAM Financial System Configuration
#Tue Mar 31 18:50:50 GMT-05:00 2026
DB_PASS=ClaudiaMH20*
DB_URL=jdbc\:mysql\://localhost\:3306/control_dinero?createDatabaseIfNotExist\=true&useSSL\=false&allowPublicKeyRetrieval\=true&serverTimezone\=UTC
DB_USER=root
