#DAM Financial System Configuration
#Sun Mar 29 12:53:28 GMT-05:00 2026
DB_PASS=12345
DB_URL=jdbc\:mysql\://localhost\:3306/control_dinero?createDatabaseIfNotExist\=true&useSSL\=false&allowPublicKeyRetrieval\=true&serverTimezone\=UTC
DB_USER=root
