# Server
server.port=8080

# Spring DataSource (Configurable externamente para portabilidad)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/control_dinero?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Configuración de Archivos PDF Múltiples
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.error.include-message=always

# JWT
jwt.secret=8e3c790cdbf6s2de6d7af870b98547fdcba0f507c8a6fcf4fca240db732c4e24
jwt.expiration=86400000

# Registro de errores para diagnóstico
logging.file.name=DAM_Actividad.log
logging.level.org.springframework=INFO
